### ISSUE TITLE
起動時のエラーについて

### ISSUE THREAD

**Issue by MiyakoCam** [0Quake/Zero-Quake#2]
**バグの説明**
起動をした時に、`app.asar/src/main.js:239:40`にて`.split(".")`のエラーが発生しています。
ただし、起動時だけのエラーなので、ダイアログを無視しても使えています。

**発生方法**
通常起動する

**Screenshots**
![20230504085059](https://user-images.githubusercontent.com/90699739/236075650-05e6647b-381e-4a92-91c1-c0f846141f40.png)

**Desktop (please complete the following information):**
 - OS: Windows10

**Additional context**
まさかのJavaScriptでこのようなアプリを作成されていて驚きました。
これからも開発がんばってください！

**Comment by 0Quake** [comment]
アプリの現在のバージョンを取得する処理のバグを修正
ビルド後の実行の際、起動時に発生するバグの改善

**Comment by 0Quake** [comment]
バグ報告ありがとうございます。今後もアプリ開発に努めてまいります。
今後ともアプリ開発へのご協力、よろしくお願いします。
