### ISSUE TITLE
Moving the map before the intensity background loads, bugs everything

### ISSUE THREAD

**Issue by YacineBoussoufa** [0Quake/Zero-Quake#3]
![image](https://github.com/0Quake/Zero-Quake/assets/46266665/c7a92754-663b-4302-81d0-0c817fa6bb45)

**Comment by 0Quake** [comment]
報告ありがとうございます
問題を再現できませんでした。おそらく、地図描画に使用しているMapLibre側の不具合と考えられます。
対応を検討します。

**Comment by 0Quake** [comment]
エラーの再現に成功し、修正しました。
この問題は、次のバージョン(v0.6.6)で改善されます。

**Comment by 0Quake** [comment]
v0.6.6にて、当該問題を修正しました。
