### ISSUE TITLE
[機能リクエスト] 初期位置に戻るボタン

### ISSUE THREAD

**Issue by 5ym** [0Quake/Zero-Quake#57]
# 提案する機能の概要

アプリ起動時の地図表示に戻るボタン

# 提案する機能がないことによる弊害

地震情報で海外などに表示が飛んだ際すぐに戻れない

# その他自由記述（任意）

起動時の画面表示を変更できる機能もあったら便利かもしれません
自分で実装できればよいのですが、すぐには実装方法がわからず
お手数をおかけしますが、なにとぞよろしくお願いいたします 🙇

**Comment by 0Quake** [comment]
メイン画面に、「起動時の位置に戻るボタン」及び「EEW等で自動的に表示位置が移った際、直前の操作位置に戻るボタン」を追加しました。
また、EEW等を表示解除した際、直前の操作位置に戻る仕様に変更しました。
（ https://github.com/0Quake/Zero-Quake/commit/9fd3dbdb946237abb81827cb8e8112d51d2d76d1 ）

ご提案ありがとうございました。私用により対応が遅れたことをお詫びします。

**Comment by 5ym** [comment]
@0Quake 
ありがとうございます！
助かります
