### ISSUE TITLE
バグ報告： 緊急地震速報の読み上げ機能について

### ISSUE THREAD

**Issue by Potatochannel** [0Quake/Zero-Quake#64]
## バグの概要
緊急地震速報が発表された際に初報に設定した読み上げ文章を、続報が発表されるたびに読み上げる。
## バグの再現
緊急地震速報の発令を待つ。
## 表示されるエラーメッセージ
エラーメッセージなし。
### **お使いの OS**
Windows11 24H2
### **お使いのソフトウェアのバージョン**
V0.7.6

### **お使いのソフトウェアの配布形式**
インストーラー版

## 自由記述（任意）
バグではないが読み上げ文章に関連して、地震の発生後の震度速報の読み上げ機能をリクエストします。

**Comment by 0Quake** [comment]
当該問題を解決しました。ご報告ありがとうございました。私用により対応が遅れたことをお詫びします。
なお、次回リリースでバグが改善しますので、ぜひ貴環境でのご確認をお願いします。
https://github.com/0Quake/Zero-Quake/commit/ddaffb6395ae25cbbfe3e26e7bb6df28c2bae367
