### ISSUE TITLE
バグ報告： 【「アプリケーションの更新」画面の、更新の開始ボタンのリンク先がおかしい】

### ISSUE THREAD

**Issue by taxi13245** [0Quake/Zero-Quake#72]
## バグの概要

設定画面からアプリケーションの更新を行うために、「更新の開始」ボタンを押したところ、[間違ったリンク先](https://0quake.github.io/ZeroQuake_IS_WebURL/download.html#download-section)に飛ばされた

## バグの再現

設定画面から、「Zero Quakeについて」→「更新の開始」を押したところ https://0quake.github.io/ZeroQuake_IS_WebURL/download.html#download-section に遷移し、404エラーが表示されました。
アプリケーションの再起動をしましたが、改善しませんでした。

## 表示されるエラーメッセージ

間違ったリンク先のスクリーンショットです。
![image](https://github.com/user-attachments/assets/6a07756b-89f9-4153-9c8e-05c35b873f22)

### **Windows 11 Home 22H2**
エディション	Windows 11 Home
バージョン	22H2
インストール日	‎2023/‎02/‎28 ‎(‎火‎)
OS ビルド	22621.3880
エクスペリエンス	Windows Feature Experience Pack 1000.22700.1020.0

### **インストーラー版**
公式サイトの「Zero Quake - ダウンロード」から2024/08/11にダウンロード

## スクリーンショット（任意）

![image](https://github.com/user-attachments/assets/d3c79800-c4e5-47b0-9b1f-b3a31bfab9e1)

**Comment by 0Quake** [comment]
ver.0.7.7以降のバージョンの設定画面で、リンク切れを起こしていました。そのため、以下のように修正を行いました。

1. アプリのリンク切れを修正しました。(e8d5477) 次回以降のバージョンでは、正しいURLに接続されます。
2. 誤ったURLから正しいURLに転送する様にしました。v0.7.7でも、正しいURLに転送されます。

これにより、再度試していただくと、従来通り正常にアップデートができるはずです。


この度はご報告いただきありがとうございました。丁寧なご報告をいただいたために、迅速な問題修正ができました。
今後とも当アプリを宜しくお願い致します。
